feat: deprecate codeheroes, foosball, crm
move4mobile/coders-workspace pull request #505
Opened 2022-09-08 06:39 UTC by mschilling

Goal: extract all apps and libs other than Gamify, into its own space/repo;

Scope of work:

- [ ] delete foosball app (including libs)
- [ ] delete codeheroes app (including libs)
- [ ] delete crm app (including libs)

Next step:

This repo will be renamed into `move4mobile/gamify-workspace`

2022-09-09 11:39 UTC, sanderelderman requested changes
`libs/gamify/.gitignore` should not be deleted? This causes the `libs/gamify/data/generated` folder to be added to the staged files which is undesirable

2022-09-09 12:39 UTC, cassshh requested changes
There were 2 `.gitignore` files removed; `apps/- & libs/gamify`.
The one within `libs/...` is reintroduced, but not the same as before. As it still includes all generated stuff.

2022-09-13 21:35 UTC, mschilling commented
> This causes the `libs/gamify/data/generated` folder to be added to the staged files which is undesirable

In doubt if this is really the case. (Will do some further checks..)

2022-09-13 21:55 UTC, mschilling commented on .github/codeql/codeql-config.yml
> +  - '**/generated'
I don't want CodeQL scanner to scan this generated folder

2022-09-14 17:40 UTC, mschilling commented
Merging now .. 🚀

2022-09-14 17:40 UTC, merged